// Minimal ESLint flat config — matches the no-framework culture: bare
// `eslint:recommended` plus a small set of rules the audit explicitly
// asked CI to enforce. Not a style police; runs on every push via
// .github/workflows/ci.yml.

import js from '@eslint/js';
import globals from 'globals';

export default [
  {
    ignores: [
      'node_modules/**',
      'dist/**',
      'test/slug_fixtures.json',  // generated by R; not source
    ],
  },
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        ...globals.browser,
        ...globals.node,
      },
    },
    rules: {
      // Catches the no-op SCRIPT_DIR-style bug from M2.2 (and many
      // other dead-code accidents). Suffix _ to opt out.
      'no-unused-vars': ['warn', {
        args: 'none',
        varsIgnorePattern: '^_',
        argsIgnorePattern: '^_',
        caughtErrors: 'none',
      }],
      // Prevents the regression class of the M5 audit finding (an
      // accidentally-shadowed variable in exportCsv).
      'no-shadow-restricted-names': 'error',
      // Empty catches are the norm in this codebase (graceful
      // degradation around localStorage, IndexedDB, navigator.clipboard);
      // allow them rather than forcing /* ignore */ everywhere.
      'no-empty': ['error', { allowEmptyCatch: true }],
      // Pin the JSON-trip-up cases that aren't covered by parsing
      // (let-as-const promotions are fine to skip).
      'no-undef': 'error',
    },
  },
];
